apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dev
  labels:
    app: test-dev
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: test-dev
  template:
    metadata:
      labels:
        app: test-dev
    spec:
      containers:
        - name: test-container
          image: 275045685638.dkr.ecr.ap-south-1.amazonaws.com/test:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          
          
            
          
---
apiVersion: v1
kind: Service
metadata:
  name: test-api-service
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: test-dev
    type:
      LoadBalancer

